name: "CI"

on:
    push:
        branches:
            - "master"
            - "develop"
    pull_request:
        branches:
            - "master"
            - "develop"

jobs:
    testing:
        name: "Run PHP-CS-Fixer, PHPStan and PHPUnit"
        runs-on: ubuntu-22.04

        steps:
            -   name: "Checkout Project"
                uses: actions/checkout@v3

            -   name: "Setup PHP"
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "8.2"
                    tools: composer:v2
                    ini-values: "memory_limit=-1"
                env:
                    fail-fast: true

            -   name: "Setup environment"
                run: cp .env.example .env

            -   name: "Install PHP dependencies"
                run: composer install

            -   name: "Generate key"
                run: php artisan key:generate

            -   name: "Run PHP-CS-Fixer"
                run: vendor/bin/php-cs-fixer fix --diff --verbose

            -   name: "Run PHPStan"
                run: vendor/bin/phpstan --memory-limit=-1

            -   name: "Run PHPUnit"
                run: vendor/bin/phpunit
